# This is for creating custom resource definition
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsdemo.devops.com # CRD name , it will be with group name

spec:
  group: devops.com # Group name
  names:
    kind: DevOpsDemo # Kind name
    plural: devopsdemos # plural name   ex: pods (kubectl get pods)
    singular: devopsdemo  # singular name ex: pod (kind: pod)
    shortNames:
      - demo
      - demos     # ex: kubectl get service 
      - devops    # ex: kubectl get svc
      - devopsdemo
  scope: Namespaced # Cluster or Namespaced 
  versions:
    - name: v1  # ex: apps/v1 
      served: true
      storage: true # storing data
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:    # Adding properties that will be used in CRD. We can add or remove properties as per our need
                  type: string
                  description: "This is the demo devops name"
                duration:
                  type: string
                  description: " This is the demo devops duration"
                mode:
                  type: string
                  description: "This is the demo devops mode"
                platform:
                  type: string
                  description: "This is the demo devops platform"
      
