kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: nginx

spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage