apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  clusterIP: None  # This will create a headless service
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306  # This is the service port
      targetPort: 3306  # This is the port in the container
