kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql
spec: 
  serviceName: mysql-service  # Attached to the service
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:  # This should be here, directly under `spec`
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:  # Environment Variables   
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret # This value comes from Secret
                key: MYSQL_ROOT_PASSWORD # This value comes from Secret

         # This is Hardcoded value, if we want to make it dynamic we can use ConfigMap   
         # - name: MYSQL_DATABASE
          #  value: mysql-demo-database

          # Value comes from ConfigMap configuration
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: MYSQL_DATABASE # This value comes from Configmap data

        # Adding VolumeMounts
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data

      # Adding Volumes
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
       # storageClassName: local-storage #Optional as we use local-storageu