kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager-rolebinding
  namespace: apache

subjects:   
- kind: User      # Type of subject is User , This is coming from service-account.yml
  name: apache-user     # name of the service account
  apiGroup: rbac.authorization.k8s.io

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role  # Type of role , This is coming from role.yml
  name: apache-manager  # name of the role
  