kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
- apiGroups: ["","*","batch","apps","rbac.authorization.k8s.io"] # * means all api groups
  resources: ["pod","deployment","service"] # What resources can be accessed
  verbs: ["get","apply","delete","watch","create","patch"]  # What actions can be performed example : kubectl get pods